name: Deploy Application with Azure File Share

on:
  push:
    branches:
      - main

env:
  TARGET_SERVER: SERVER_IP_OCI_1   # Defina aqui o servidor para o deploy
  SERVICE_IMAGE: nginx:latest       # Imagem do serviço
  SERVICE_PORT: 80                  # Porta exposta pelo serviço
  VOLUME_DEST: /usr/share/nginx/html # Caminho dentro do contêiner para o volume

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Obter o nome do repositório dinamicamente
      - name: Set Repository Name as Environment Variable
        id: repo_name
        run: |
          echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV
          echo "SERVICE_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV

      # Obter o SERVER_IP dinamicamente com base no TARGET_SERVER
      - name: Set Server IP
        run: |
          echo "SERVER_IP=${{ secrets[env.TARGET_SERVER] }}" >> $GITHUB_ENV

      # Checkout do repositório
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Baixar e configurar o AzCopy
      - name: Install AzCopy
        run: |
          wget -O azcopy.tar.gz https://aka.ms/downloadazcopylinux
          tar -xf azcopy.tar.gz
          sudo cp ./azcopy_linux_amd64_*/azcopy /usr/local/bin/azcopy
          azcopy --version

      # Fazer upload do conteúdo local para o Azure File Share
      - name: Upload Content to Azure File Share
        env:
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
          AZURE_FILE_SHARE: ${{ secrets.AZURE_FILE_SHARE }}
        run: |
          azcopy sync ./config "https://${{ env.AZURE_STORAGE_ACCOUNT }}.file.core.windows.net/${{ env.AZURE_FILE_SHARE }}/${{ env.REPO_NAME }}" \
            --recursive \
            --dest-key=${{ secrets.AZURE_STORAGE_KEY }}

      # Configurar a chave SSH
      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # Configurar e executar o Docker Compose no servidor remoto
      - name: Deploy Application with Docker Compose
        env:
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          AZURE_FILE_SHARE: ${{ secrets.AZURE_FILE_SHARE }}
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ env.SERVER_IP }} << EOF
            set -e

            # Variáveis
            AZURE_FILE_DIR=${{ env.REPO_NAME }}
            DEPLOY_DIR=/$AZURE_FILE_DIR

            # Criar diretório para o Docker Compose
            sudo mkdir -p $DEPLOY_DIR

            # Gerar arquivo docker-compose.yml
            cat <<EOT > $DEPLOY_DIR/docker-compose.yml
            version: '3.8'

            services:
              ${SERVICE_NAME}:
                image: ${SERVICE_IMAGE}
                container_name: ${SERVICE_NAME}
                ports:
                  - "${SERVICE_PORT}:${SERVICE_PORT}"
                volumes:
                  - azurefiles:${VOLUME_DEST}

            volumes:
              azurefiles:
                driver: azurefile
                driver_opts:
                  share_name: $AZURE_FILE_SHARE
                  storage_account_name: $AZURE_STORAGE_ACCOUNT
                  storage_account_key: $AZURE_STORAGE_KEY
            EOT

            # Subir o Docker Compose
            cd $DEPLOY_DIR
            docker-compose up -d
          EOF
